# Configuration link with a heralded model using a two click protocol, a noisy generic qdevice
qdevice_cfg: &qdevice_cfg
  num_qubits: 2
  # coherence times (same for each qubit)
  T1: 10_000_000_000
  T2: 10_000_000_000

  # gate execution times
  init_time: 10_000
  single_qubit_gate_time: 1_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000

  # noise model
  single_qubit_gate_depolar_prob: 0
  two_qubit_gate_depolar_prob: 0

stacks:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

link_cfg: &link_cfg
    # total length [km] of heralded connection (i.e. sum of fibers on both sides on midpoint station).
    length: 100.0
    # probability that photons are lost when entering connection the connection on either side.
    p_loss_init: 0.1
    # attenuation coefficient [dB/km] of fiber on either side.
    p_loss_length: 0.1
    # speed of light [km/s] in fiber on either side.
    speed_of_light: 200_000
    # dark-count probability per detection
    dark_count_probability: 0
    # probability that the presence of a photon leads to a detection event
    detector_efficiency: 1.0
    # Hong-Ou-Mandel visibility of photons that are being interfered (measure of photon indistinguishability)
    visibility: 0.1
    # determines whether photon-number-resolving detectors are used for the Bell-state measurement
    num_resolving: False

links:
  - stack1: Alice
    stack2: Bob
    typ: heralded
    cfg:
      <<: *link_cfg

clinks:
  - stack1: Alice
    stack2: Bob
    typ: instant
