# Configuration link with a heralded model using a two click protocol, a noisy generic qdevice
qdevice_cfg: &qdevice_cfg
  num_qubits: 2

  # noise model
  single_qubit_gate_depolar_prob: 0.01
  two_qubit_gate_depolar_prob: 0.1

stacks:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

link_cfg:
  &link_cfg # total length [km] of heralded connection (i.e. sum of fibers on both sides on midpoint station).
  length: 1.0
  # probability that photons are lost when entering connection the connection on either side.
  p_loss_init: 0
  # attenuation coefficient [dB/km] of fiber on either side.
  p_loss_length: 0.25

links:
  - stack1: Alice
    stack2: Bob
    typ: heralded
    cfg:
      <<: *link_cfg

clinks:
  - stack1: Alice
    stack2: Bob
    typ: instant
